extends CharacterBody2D

## Top-down player. WASD + arrow-key movement via move_and_slide() (keys polled, so no
## custom InputMap). Its sprite is generated by PixelArt; it flips to face the way it
## moves and bobs while walking, with a soft drop shadow on the ground.

const PixelArt = preload("res://scripts/PixelArt.gd")

const SKIN := Color8(240, 200, 162)
const HAIR := Color8(74, 50, 34)
const SHIRT := Color8(86, 150, 92)
const PANTS := Color8(70, 80, 112)

const REST_Y := -2.0  # sprite centre offset so the feet sit at the body origin

@export var speed: float = 200.0

@onready var _visual: Sprite2D = $Visual
@onready var _shadow: Sprite2D = $Shadow

var _bob: float = 0.0

func _ready() -> void:
	_visual.texture = PixelArt.character(SKIN, HAIR, SHIRT, PANTS)
	_visual.position = Vector2(0, REST_Y)
	_shadow.texture = PixelArt.shadow(16, 7)
	_shadow.position = Vector2(0, 12)

func _physics_process(delta: float) -> void:
	var direction := Vector2.ZERO
	if Input.is_key_pressed(KEY_W) or Input.is_key_pressed(KEY_UP):
		direction.y -= 1.0
	if Input.is_key_pressed(KEY_S) or Input.is_key_pressed(KEY_DOWN):
		direction.y += 1.0
	if Input.is_key_pressed(KEY_A) or Input.is_key_pressed(KEY_LEFT):
		direction.x -= 1.0
	if Input.is_key_pressed(KEY_D) or Input.is_key_pressed(KEY_RIGHT):
		direction.x += 1.0
	velocity = direction.normalized() * speed
	move_and_slide()

	if direction.x < 0.0:
		_visual.flip_h = true
	elif direction.x > 0.0:
		_visual.flip_h = false
	if direction != Vector2.ZERO:
		_bob += delta * 11.0
		_visual.position.y = REST_Y - absf(sin(_bob)) * 2.0  # a little walking hop
	else:
		_bob = 0.0
		_visual.position.y = REST_Y
